[package]
name = "salieri"
description = "Amadeus services consumer"
version = "0.1.2"
edition = "2021"

[dependencies]
mozart      = { path = "../Mozart" }
serde       = "1"
env_logger  = "0.9.0"
log         = "0.4.16"
anyhow      = "1"

[dependencies.tokio]
version = "1.18"
features = ["full"]

[dependencies.celery]
git = "https://github.com/Qeenon/rusty-celery.git"
branch = "mawa"
