[package]
name        = "amadeus"
version     = "2.29.1"
authors     = [ "Qeenon" ]
repository  = "https://github.com/Qeenon/Amadeus"
readme      = "README.md"
keywords    = [ "discord", "bot" ]
edition     = "2018"
description = "memory storage and artificial intelligence system"
license     = "ISC AND MPL-v2"

[features]
default = []
w3g_rs  = ["w3grs"]

[dependencies]
rand                = "0.7.3"
chrono              = "0.4.19"
chrono-tz           = "0.5.3"
argparse            = "0.2.2"
tracing             = "0.1.22"
tracing-log         = "0.1.1"
tracing-futures     = "0.2.4"
tracing-subscriber  = "0.2.15"
regex               = "1.4.2"
serde               = "1.0.117"
serde_derive        = "1.0.117"
serde_json          = "1.0.59"
serde_dhall         = "0.9.0"
lazy_static         = "1.4.0"
ucd                 = "0.1.1"
comfy-table         = "1.3.0"
async-std           = "1.7.0"
futures-util        = "0.3.8"
qrcode              = "0.12.0"
cannyls             = "0.10.0"
bincode             = "1.3.1"
itertools           = "0.9.0"
uuid                = "0.8.1"
tch                 = "0.3.0"
plotters            = "0.3.0"
rust-bert           = "0.12.0"
rudano              = "0.1.0"
eyre                = "0.6.3"
async-recursion     = "0.3.1"
unic-langid         = "0.9.0"
fluent-templates    = "0.5.16"
sled                = "0.34.6"

reqwest   = { version = "0.10.9", features = ["json", "blocking"] }
ical      = { version = "0.7.0",  features = ["ical"] }
markov    = { version = "1.1.0",  features = ["yaml"] }

[dependencies.serenity]
default-features = false
version = "0.9.2"
features = [ "cache"
           , "builder"
           , "model"
           , "framework"
           , "standard_framework"
           , "voice"
           , "client"
           , "http"
           , "native_tls_backend"
           , "utils"
           , "collector" ]

[dependencies.w3grs]
git = "https://github.com/Qeenon/w3grs.git"
branch = "mawa"
optional = true

[dependencies.kathoey]
git = "https://github.com/Qeenon/Kathoey"
branch = "mawa"

# wait for serenity, hyper, reqwest support for 0.3
[dependencies.tokio]
version = "0.2.23"
features = ["full", "blocking", "sync"]
