[package]
name        = "amadeus"
version     = "4.5.13"
authors     = [ "Qeenon" ]
repository  = "https://github.com/Qeenon/Amadeus"
readme      = "README.md"
keywords    = [ "discord", "bot" ]
edition     = "2018"
description = "memory storage and artificial intelligence system"
license     = "AGPL-3.0-or-later"

[features]
default = ["flo"]
flo = ["tonic", "hex", "tokio-compat-02", "flo-grpc"]

[dependencies]
chrono              = "0.4"
chrono-tz           = "0.5"
tracing             = "0.1"
tracing-log         = "0.1"
tracing-futures     = "0.2"
tracing-subscriber  = "0.2"
regex               = "1.4"
serde               = "1.0"
serde_derive        = "1.0"
serde_json          = "1.0"
once_cell           = "1.7"
ucd                 = "0.1"
comfy-table         = "2.1"
async-std           = "1.9"
futures-util        = "0.3"
qrcode              = "0.12"
cannyls             = "0.10"
bincode             = "1.3"
itertools           = "0.10"
uuid                = "0.8"

# rust bert needs update
tch                 = "0.3"
plotters            = "0.3"
rust-bert           = "0.14"
rudano              = "0.1"
eyre                = "0.6"
async-recursion     = "0.3"
unic-langid         = "0.9"
fluent-templates    = "0.6"
sled                = "0.34"
kathoey             = "1.0"
songbird            = "0.1.5"
serde_dhall         = "0.10.0"

rand    = { version = "0.8",  features = ["std", "std_rng"] }
reqwest = { version = "0.11", features = ["json", "blocking"] }
ical    = { version = "0.7",  features = ["ical"] }
markov  = { version = "1.1",  features = ["yaml"] }

[dependencies.serenity]
default-features = false
version = "0.10"
features = [ "cache"
           , "builder"
           , "model"
           , "framework"
           , "standard_framework"
           , "voice"
           , "client"
           , "http"
           , "native_tls_backend"
           , "utils"
           , "collector" ]

# using fork because I will update tokens&rules
# in the same time with code
# related: https://github.com/bminixhofer/nlprule/issues/49
[dependencies.nlprule]
git = "https://github.com/Masha/nlprule.git"
branch = "main"

[dependencies.hex]
version = "0.4"
optional = true

# flo needs update to 0.4 first
[dependencies.tonic]
version = "0.3"
optional = true

[dependencies.tokio-compat-02]
version = "0.2"
optional = true

[dependencies.flo-grpc]
git = "https://github.com/Masha/flo-grpc.git"
branch = "main"
optional = true

[dependencies.tokio]
version = "1.4"
features = ["full"]
