[package]
name        = "amadeus"
version     = "3.0.2"
authors     = [ "Qeenon" ]
repository  = "https://github.com/Qeenon/Amadeus"
readme      = "README.md"
keywords    = [ "discord", "bot" ]
edition     = "2018"
description = "memory storage and artificial intelligence system"
license     = "ISC AND MPL-v2"

[features]
default = []
flo = ["flo-grpc", "tonic", "hex"]

[dependencies]
chrono              = "0.4"
chrono-tz           = "0.5"
argparse            = "0.2"
tracing             = "0.1"
tracing-log         = "0.1"
tracing-futures     = "0.2"
tracing-subscriber  = "0.2"
regex               = "1.4"
serde               = "1.0"
serde_derive        = "1.0"
serde_json          = "1.0"
serde_dhall         = "0.9"
lazy_static         = "1.4"
ucd                 = "0.1"
comfy-table         = "1.4"
async-std           = "1.8"
futures-util        = "0.3"
qrcode              = "0.12"
cannyls             = "0.10"
bincode             = "1.3"
itertools           = "0.9"
uuid                = "0.8"
tch                 = "0.3"
plotters            = "0.3"
rust-bert           = "0.12"
rudano              = "0.1"
eyre                = "0.6"
async-recursion     = "0.3"
unic-langid         = "0.9"
fluent-templates    = "0.5"
sled                = "0.34"

rand      = { version = "0.8",  features = ["std", "std_rng"] }
reqwest   = { version = "0.10", features = ["json", "blocking"] }
ical      = { version = "0.7",  features = ["ical"] }
markov    = { version = "1.1",  features = ["yaml"] }

[dependencies.serenity]
default-features = false
version = "0.9"
features = [ "cache"
           , "builder"
           , "model"
           , "framework"
           , "standard_framework"
           , "voice"
           , "client"
           , "http"
           , "native_tls_backend"
           , "utils"
           , "collector" ]

[dependencies.kathoey]
git = "https://github.com/Qeenon/Kathoey"
branch = "mawa"

[dependencies.hex]
version = "0.4"
optional = true

[dependencies.tonic]
version = "0.3"
optional = true

# private source (optional)
[dependencies.flo-grpc]
path = "crates/flo-grpc"
optional = true

# wait for serenity, hyper, reqwest support for 0.3
[dependencies.tokio]
version = "0.2"
features = ["full", "blocking", "sync"]
