[package]
name        = "amadeus"
version     = "2.11.28"
authors     = [ "Qeenon" ]
repository  = "https://github.com/Qeenon/Amadeus"
readme      = "README.md"
keywords    = [ "discord", "bot" ]
edition     = "2018"
description = "memory storage and artificial intelligence system"
license     = "ISC AND MPL-v2"

[dependencies]
rand          = "0.7.3"
chrono        = "0.4.13"
argparse      = "0.2.2"
log           = "0.4.11"
env_logger    = "0.7.1"
regex         = "1.3.9"
serde         = "1.0.115"
serde_derive  = "1.0.115"
serde_json    = "1.0.57"
serde_dhall   = "0.6.0"
lazy_static   = "1.4.0"
markov        = "1.1.0"
ucd           = "0.1.1"
comfy-table   = "1.0.0"
async-std     = "1.6.3"
futures-util  = "0.3.5"
qrcode        = "0.12.0"
cannyls       = "0.10.0"
bincode       = "1.3.1"
itertools     = "0.9.0"
anyhow        = "1.0.32"
uuid          = "0.8.1"
tch           = "0.2.0"

reqwest = { version = "0.10.7", features = ["json", "blocking"] }
ical    = { version = "0.6.0",  features = ["ical"] }

[dependencies.tokio]
version = "0.2.22"
features = ["full", "blocking", "sync"]

[dependencies.rust-bert]
git = "https://github.com/guillaume-be/rust-bert.git"
branch = "master"

[dependencies.serenity]
default-features = false
git = "https://github.com/serenity-rs/serenity.git"
branch = "current"
features = [ "cache"
           , "builder"
           , "model"
           , "framework"
           , "standard_framework"
           , "voice"
           , "client"
           , "http"
           , "native_tls_backend"
           , "utils"
           , "collector" ]
