[workspace]
members = [
  "Mozart",
  "Amadeus",
  "Salieri"
]

[profile.release]
opt-level = 3
overflow-checks = false
debug-assertions = false
lto = "thin"

# using thin due active development, will be fat later
# lto = "fat"
