[package]
name            = "amadeus"
version         = "7.4.3"
authors         = [ "Miezhiko" ]
repository      = "https://github.com/Miezhiko/Amadeus"
readme          = "README.md"
keywords        = [ "discord", "bot" ]
edition         = "2021"
description     = "memory storage and artificial intelligence system"
license         = "AGPL-3.0-only"
rust-version    = "1.56.0"

[features]
default = ["trackers", "flo"]
trackers = []
flo = ["tonic", "hex", "flo-grpc"]
voice_analysis = ["dasp_interpolate", "dasp_signal", "deepspeech"]
full = ["flo", "voice_analysis", "trackers"]

[dependencies]
chrono              = "0.4"
chrono-tz           = "0.6"
tracing             = "0.1"
tracing-log         = "0.1"
tracing-futures     = "0.2"
tracing-subscriber  = "0.3"
regex               = "1.5"
serde               = "1.0"
serde_derive        = "1.0"
serde_json          = "1.0"
serde_yaml          = "0.8"
once_cell           = "1.8"
ucd                 = "0.1"
comfy-table         = "4.1"
async-std           = "1.10"
futures-util        = "0.3"
qrcode              = "0.12"
cannyls             = "0.10"
bincode             = "1.3"
itertools           = "0.10"
plotters            = "0.3"
anyhow              = "1"
async-recursion     = "0.3"
unic-langid         = "0.9"
fluent-templates    = "0.6"
sled                = "0.34"
kathoey             = "1.0.10"
serde_dhall         = "0.10"
nlprule             = "0.6.4"

rand    = { version = "0.8",  features = ["std", "std_rng"] }
reqwest = { version = "0.11.6", features = ["json", "blocking"] }
ical    = { version = "0.7",  features = ["ical"] }
markov  = { version = "1.1",  features = ["yaml"] }

tch = "0.6.1"
[dependencies.rust-bert]
default-features = false
git = "https://github.com/guillaume-be/rust-bert.git"
branch = "master"

[dependencies.songbird]
default-features = false
git = "https://github.com/serenity-rs/songbird.git"
branch = "current"
features = [ "yt-dlp"
           , "serenity-rustls"
           , "driver"
           , "gateway"
           ]

[dependencies.serenity]
default-features = false
version = "0.10.9"
features = [ "cache"
           , "builder"
           , "model"
           , "framework"
           , "standard_framework"
           , "voice"
           , "client"
           , "http"
           , "native_tls_backend"
           , "utils"
           , "collector"
           , "unstable_discord_api"
           ]

[dependencies.hex]
version = "0.4"
optional = true

# should be updated with flo
[dependencies.tonic]
version = "0.4"
optional = true

[dependencies.flo-grpc]
git = "https://github.com/w3champions/flo-grpc.git"
branch = "main"
optional = true

[dependencies.tokio]
version = "1.12"
features = ["full"]

[dependencies.dasp_signal]
version = "0.11"
optional = true

[dependencies.dasp_interpolate]
version = "0.11"
optional = true
features = ["linear"]

[dependencies.deepspeech]
version = "0.9"
optional = true

[profile.release]
opt-level = 3
lto = false
