[package]
name        = "amadeus"
version     = "6.0.0"
authors     = [ "Qeenon" ]
repository  = "https://github.com/Qeenon/Amadeus"
readme      = "README.md"
keywords    = [ "discord", "bot" ]
edition     = "2018"
description = "memory storage and artificial intelligence system"
license     = "AGPL-3.0-only"

[features]
default = ["flo"]
full = ["flo", "voice_analysis"]
flo = ["tonic", "hex", "flo-grpc"]
voice_analysis = ["dasp_interpolate", "dasp_signal", "deepspeech"]

[dependencies]
chrono              = "0.4"
chrono-tz           = "0.5"
tracing             = "0.1"
tracing-log         = "0.1"
tracing-futures     = "0.2"
tracing-subscriber  = "0.2"
regex               = "1.4"
serde               = "1.0"
serde_derive        = "1.0"
serde_json          = "1.0"
once_cell           = "1.7"
ucd                 = "0.1"
comfy-table         = "2.1"
async-std           = "1.9"
futures-util        = "0.3"
qrcode              = "0.12"
cannyls             = "0.10"
bincode             = "1.3"
itertools           = "0.10"
plotters            = "0.3"
rudano              = "0.1"
anyhow              = "1"
async-recursion     = "0.3"
unic-langid         = "0.9"
fluent-templates    = "0.6"
sled                = "0.34"
kathoey             = "1.0.6"
songbird            = "0.2.0-beta.2"
serde_dhall         = "0.10"
nlprule             = "0.6.4"

# rust bert needs update
tch                 = "0.4.1"
#rust-bert           = "0.15"
rust-bert = { git = "https://github.com/guillaume-be/rust-bert", branch = "conversation_model_fox" }

rand    = { version = "0.8",  features = ["std", "std_rng"] }
reqwest = { version = "0.11", features = ["json", "blocking"] }
ical    = { version = "0.7",  features = ["ical"] }
markov  = { version = "1.1",  features = ["yaml"] }

[dependencies.serenity]
default-features = false
version = "0.10.7"
features = [ "cache"
           , "builder"
           , "model"
           , "framework"
           , "standard_framework"
           , "voice"
           , "client"
           , "http"
           , "native_tls_backend"
           , "utils"
           , "collector" ]

[dependencies.hex]
version = "0.4"
optional = true

[dependencies.tonic]
version = "0.4"
optional = true

[dependencies.flo-grpc]
git = "https://github.com/Masha/flo-grpc.git"
branch = "main"
optional = true

[dependencies.tokio]
version = "1.6"
features = ["full"]

[dependencies.dasp_signal]
version = "0.11"
optional = true

[dependencies.dasp_interpolate]
version = "0.11"
optional = true
features = ["linear"]

[dependencies.deepspeech]
version = "0.9"
optional = true

[profile.release]
opt-level = 3
lto = false
