version: 2.1

jobs:
  test:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run: bash eat-some-dirt.sh
      - run: cargo --version
      - run: cargo test

workflows:
  default:
    jobs:
      - test:
          name: build_test_debug
