version: 2.1

jobs:
  test:
    docker:
      - image: cimg/rust:1.58.1
    steps:
      - checkout
      - run: cargo --version
      - run: cargo test

workflows:
  default:
    jobs:
      - test:
          name: build_test_debug
