[package]
name = "mozart"
description = "Amadeus services library"
version = "0.2.14"
edition = "2021"

[lib]
doctest = false

[dependencies]
serde           = "1"
log             = "0.4.17"
anyhow          = "1"
once_cell       = "1.13.0"
rand            = "0.8.5"
chrono          = "0.4.19"
bincode         = "2.0.0-rc.1"
regex           = "1.6.0"
async-recursion = "1.0.0"
tch              = "0.8"

[dependencies.rust-bert]
default-features = false
git = "https://github.com/guillaume-be/rust-bert.git"
branch = "master"
features = [ "remote" ]

[dependencies.tokio]
version = "1.20.0"
features = ["full"]

[dependencies.celery]
git = "https://github.com/Qeenon/rusty-celery.git"
branch = "mawa"
